blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogPostListView, BlogPostDetailView, BlogPostCreateView, BlogPostUpdateView, BlogPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogPostListView.as_view(), name='blogpost_list'),
    path('blog/<slug:slug>/', BlogPostDetailView.as_view(), name='blogpost_detail'),
    path('create/', BlogPostCreateView.as_view(), name='blogpost_form'),
    path('blog/<int:pk>/update/', BlogPostUpdateView.as_view(), name='blogpost_update'),
    path('blog/<int:pk>/delete/', BlogPostDeleteView.as_view(), name='blogpost_delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('catalog/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('catalog/create/', ProductCreateView.as_view(), name='product_form'),
    path('catalog/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('catalog/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path("category/", CategoryListView.as_view(), name="category_list"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import email_verification, ProfileView, PasswordResetView, RegisterView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("password-reset/", PasswordResetView.as_view(), name="password_reset"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="Email")
    phone = models.CharField(
        max_length=35,
        verbose_name="Телефон",
        **NULLABLE,
        help_text="Введите номер телефона",
    )
    country = models.CharField(
        max_length=50, verbose_name="Страна", help_text="Укажите страну"
    )
    avatar = models.ImageField(
        upload_to="users/avatars/",
        verbose_name="Аватар",
        **NULLABLE,
        help_text="Загрузите аватар",
    )

    token = models.CharField(
        max_length=75,
        verbose_name="Token",
        **NULLABLE,
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import HiddenInput

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ["email", "first_name", "last_name", "phone", "avatar", "country"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password"].widget = HiddenInput()

users/views.py
import random
import secrets
import string

from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, UpdateView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        host = self.request.get_host()
        user.token = token
        user.save()
        url = f"http://{host}/users/email-confirm/{token}/"
        send_mail(
            subject="Подтверждение регистрации",
            message=f"Добро пожаловать на сайт! Для подтверждения регистрации перейди по ссылке: {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class PasswordResetView(View):
    form_class = PasswordResetForm
    template_name = "users/password_reset.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            try:
                user = User.objects.get(email=email)
                new_password = "".join(
                    random.choices(string.ascii_letters + string.digits, k=8)
                )
                user.password = make_password(new_password)
                user.save()

                send_mail(
                    subject="Восстановление пароля",
                    message=f"Ваш новый пароль: {new_password}",
                    from_email=EMAIL_HOST_USER,
                    recipient_list=[email],
                )
                return redirect(reverse("users:login"))
            except User.DoesNotExist:
                form.add_error("email", "Пользователь с таким email не найден")
        return render(request, self.template_name, {"form": form})


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = "users/profile.html"
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/password_reset.html
{% extends "catalog/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <h2>Восстановление пароля</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Восстановить пароль</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends "catalog/base.html" %}
{% load my_tags %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="card-header bg-primary text-white text-center" style="border-radius: 30px 30px 0 0;">
                    <h2>Аватар</h2>
                </div>
                <div class="card shadow-sm " style="border-radius: 30px;">
                    {% if object.avatar %}
                        <img src="{{ object.avatar | media_filter }}" alt="avatar">
                    {% else %}
                        <img src="{% static 'media_default/default_avatar.png' %}" alt="default_avatar">
                    {% endif %}
                </div>
                <div class="card-footer bg-primary text-white text-center" style="border-bottom-left-radius: 30px; border-bottom-right-radius: 30px;" >
                    <p class="card-text" >{{ object.last_name }} {{ object.first_name }} | Тел.: {{ object.phone }}</p>
                </div>
            </div>
            <div class="col-lg-6 col-md-8">
                <div class="card shadow-sm " style="border-radius: 30px;">
                    <div class="card-header bg-primary text-white text-center" style="border-radius: 30px 30px 0 0;">
                        <h2>Профиль</h2>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-success" type="submit">Сохранить</button>
                            <a class="btn btn-outline-secondary" href="{% url 'catalog:product_list' %}"
                               role="button">Назад</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
 {% extends "catalog/base.html" %}
{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8">
                <div class="card shadow-sm " style="border-radius: 30px;">
                    <div class="card-header bg-primary text-white text-center" style="border-radius: 30px 30px 0 0;">
                        <h2>Регистрация</h2>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-success" type="submit">Зарегистрироваться</button>
                            <a class="btn btn-outline-secondary" href="{% url 'catalog:product_list' %}"
                               role="button">Назад</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Зарегистрироваться
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock %}